/*
 * testgen.c - kdality test-gen subcommand.
 *
 * Auto-generates KUnit test stubs from a .kdc driver file.
 *
 *   kdality test-gen <file.kdc> [-o <outdir>]
 *
 * Scans the .kdc for event handlers and generates a KUnit test file
 * with one test case per handler, plus setup/teardown scaffolding.
 */

#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define NAME_LEN 64
#define MAX_HANDLERS 32

static int is_safe_filename_component(const char *s)
{
	if (!s || !*s)
		return 0;
	if (strstr(s, "..") || strchr(s, '/') || strchr(s, '\\'))
		return 0;
	return 1;
}

static int is_safe_outdir(const char *s)
{
	if (!s || !*s)
		return 0;
	if (strstr(s, "..") || strchr(s, '\\') || strchr(s, '\n') ||
	    strchr(s, '\r'))
		return 0;
	return 1;
}

struct handler_info {
	char event[NAME_LEN]; /* e.g. "probe", "read", "power on" */
	char label[NAME_LEN]; /* e.g. "probe", "read", "power_on" */
};

struct kdc_info {
	char driver_name[NAME_LEN];
	char device_name[NAME_LEN];
	struct handler_info handlers[MAX_HANDLERS];
	int nhandlers;
};

/* ── .kdc scanner ────────────────────────────────────────────────── */

static int parse_kdc(const char *path, struct kdc_info *info)
{
	FILE *fp;
	char line[512];

	memset(info, 0, sizeof(*info));

	fp = fopen(path, "r");
	if (!fp) {
		fprintf(stderr, "test-gen: cannot open '%s': %s\n", path,
			strerror(errno));
		return -1;
	}

	while (fgets(line, sizeof(line), fp)) {
		char *p = line;
		while (*p == ' ' || *p == '\t')
			p++;

		if (*p == '\n' || *p == '\0' || *p == '/')
			continue;

		/* driver NAME for DEVICE */
		if (strncmp(p, "driver ", 7) == 0) {
			sscanf(p, "driver %63s for %63[^ {]", info->driver_name,
			       info->device_name);
			continue;
		}

		/* on <event> [<extra>] { */
		if (strncmp(p, "on ", 3) == 0 &&
		    info->nhandlers < MAX_HANDLERS) {
			char event[NAME_LEN] = "";
			char extra[NAME_LEN] = "";
			struct handler_info *h =
				&info->handlers[info->nhandlers];

			sscanf(p + 3, "%63s %63[^{ \n]", event, extra);

			if (extra[0] && strcmp(extra, "{") != 0) {
				snprintf(h->event, NAME_LEN, "%s %s", event,
					 extra);
				snprintf(h->label, NAME_LEN, "%s_%s", event,
					 extra);
			} else {
				strncpy(h->event, event, NAME_LEN - 1);
				strncpy(h->label, event, NAME_LEN - 1);
			}
			info->nhandlers++;
			continue;
		}
	}

	fclose(fp);

	if (!info->driver_name[0]) {
		fprintf(stderr, "test-gen: no 'driver' found in '%s'\n", path);
		return -1;
	}

	if (!is_safe_filename_component(info->driver_name)) {
		fprintf(stderr,
			"test-gen: invalid driver name '%s' in '%s'\n",
			info->driver_name, path);
		return -1;
	}

	return 0;
}

/* ── KUnit test generation ───────────────────────────────────────── */

static int generate_kunit(const struct kdc_info *info, const char *outdir)
{
	char path[512];
	FILE *fp;

	if (!is_safe_outdir(outdir)) {
		fprintf(stderr, "test-gen: invalid output directory '%s'\n",
			outdir ? outdir : "(null)");
		return -1;
	}

	if (!is_safe_filename_component(info->driver_name)) {
		fprintf(stderr, "test-gen: invalid driver name '%s'\n",
			info->driver_name);
		return -1;
	}

	snprintf(path, sizeof(path), "%s/test_%s.c", outdir, info->driver_name);
	fp = fopen(path, "w");
	if (!fp) {
		fprintf(stderr, "test-gen: cannot create '%s': %s\n", path,
			strerror(errno));
		return -1;
	}

	/* Header */
	fprintf(fp, "// SPDX-License-Identifier: GPL-2.0\n");
	fprintf(fp, "/*\n");
	fprintf(fp, " * test_%s.c - KUnit tests for %s driver\n",
		info->driver_name, info->driver_name);
	fprintf(fp, " * Auto-generated by: kdality test-gen\n");
	fprintf(fp, " *\n");
	fprintf(fp, " * Device: %s\n", info->device_name);
	fprintf(fp, " * Handlers tested: %d\n", info->nhandlers);
	fprintf(fp, " */\n\n");

	fprintf(fp, "#include <kunit/test.h>\n");
	fprintf(fp, "#include <linux/module.h>\n\n");

	/* Forward declarations (user fills in actual includes) */
	fprintf(fp, "/* TODO: Include your generated driver header */\n");
	fprintf(fp, "/* #include \"%s.h\" */\n\n", info->driver_name);

	/* Setup / teardown */
	fprintf(fp, "struct %s_test_ctx {\n", info->driver_name);
	fprintf(fp, "\t/* TODO: Add test context fields */\n");
	fprintf(fp, "\tint dummy;\n");
	fprintf(fp, "};\n\n");

	fprintf(fp, "static int %s_test_init(struct kunit *test)\n",
		info->driver_name);
	fprintf(fp, "{\n");
	fprintf(fp, "\tstruct %s_test_ctx *ctx;\n\n", info->driver_name);
	fprintf(fp, "\tctx = kunit_kzalloc(test, sizeof(*ctx), GFP_KERNEL);\n");
	fprintf(fp, "\tKUNIT_ASSERT_NOT_ERR_OR_NULL(test, ctx);\n");
	fprintf(fp, "\ttest->priv = ctx;\n\n");
	fprintf(fp, "\treturn 0;\n");
	fprintf(fp, "}\n\n");

	/* Test cases - one per handler */
	for (int i = 0; i < info->nhandlers; i++) {
		const struct handler_info *h = &info->handlers[i];

		fprintf(fp, "static void %s_test_%s(struct kunit *test)\n",
			info->driver_name, h->label);
		fprintf(fp, "{\n");
		fprintf(fp, "\t/* Test: on %s handler */\n", h->event);
		fprintf(fp, "\t/* TODO: Set up mock device, call handler, "
			    "assert register state */\n");
		fprintf(fp, "\tKUNIT_EXPECT_EQ(test, 0, 0); "
			    "/* placeholder */\n");
		fprintf(fp, "}\n\n");
	}

	/* Test suite registration */
	fprintf(fp, "static struct kunit_case %s_test_cases[] = {\n",
		info->driver_name);
	for (int i = 0; i < info->nhandlers; i++) {
		fprintf(fp, "\tKUNIT_CASE(%s_test_%s),\n", info->driver_name,
			info->handlers[i].label);
	}
	fprintf(fp, "\t{}\n");
	fprintf(fp, "};\n\n");

	fprintf(fp, "static struct kunit_suite %s_test_suite = {\n",
		info->driver_name);
	fprintf(fp, "\t.name = \"%s\",\n", info->driver_name);
	fprintf(fp, "\t.init = %s_test_init,\n", info->driver_name);
	fprintf(fp, "\t.test_cases = %s_test_cases,\n", info->driver_name);
	fprintf(fp, "};\n\n");

	fprintf(fp, "kunit_test_suites(&%s_test_suite);\n\n",
		info->driver_name);
	fprintf(fp, "MODULE_LICENSE(\"GPL\");\n");
	fprintf(fp, "MODULE_DESCRIPTION(\"KUnit tests for %s driver\");\n",
		info->driver_name);

	fclose(fp);
	return 0;
}

/* ── help ────────────────────────────────────────────────────────── */

static void testgen_help(void)
{
	fprintf(stderr,
		"Usage: kdality test-gen <file.kdc> [options]\n\n"
		"Generate KUnit test stubs from a .kdc driver file.\n\n"
		"Options:\n"
		"  -o <dir>    output directory (default: .)\n"
		"  -h, --help  show this help\n\n"
		"Example:\n"
		"  kdality test-gen examples/kdc_hello/uart_hello.kdc -o tests/\n\n"
		"Output:\n"
		"  tests/test_uart_hello_driver.c    KUnit test file\n");
}

int kdality_testgen(int argc, char *const argv[])
{
	const char *input = NULL;
	const char *outdir = ".";

	for (int i = 0; i < argc; i++) {
		if (strcmp(argv[i], "-h") == 0 ||
		    strcmp(argv[i], "--help") == 0) {
			testgen_help();
			return 0;
		} else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
			outdir = argv[++i];
		} else if (argv[i][0] != '-') {
			input = argv[i];
		}
	}

	if (!input) {
		fprintf(stderr, "test-gen: no input .kdc file\n\n");
		testgen_help();
		return 1;
	}

	struct kdc_info info;
	if (parse_kdc(input, &info) != 0)
		return 1;

	if (generate_kunit(&info, outdir) != 0)
		return 1;

	printf("Generated %s/test_%s.c\n", outdir, info.driver_name);
	printf("  driver: %s\n", info.driver_name);
	printf("  test cases: %d\n", info.nhandlers);
	for (int i = 0; i < info.nhandlers; i++)
		printf("    - %s_test_%s\n", info.driver_name,
		       info.handlers[i].label);

	return 0;
}
