# KDALTargets.cmake
# Defines exported CMake targets for the KDAL package.
#
# This file is generated by cmake --install and should not be hand-edited
# in installed trees. The source-tree version is maintained here for
# in-source (non-installed) usage via add_subdirectory().
#
# Targets defined:
#   KDAL::libkdal   — KDAL kernel-space runtime library (static)
#   KDAL::libkdalc  — KDAL compiler library (static)
#   KDAL::kdality   — unified toolchain binary (imported executable)
#   KDAL::kdalc     — standalone compiler binary (imported executable)

cmake_minimum_required(VERSION 3.16)

# Guard against re-inclusion
if(TARGET KDAL::libkdal)
    return()
endif()

# ── Compute paths relative to this file ───────────────────────────────
get_filename_component(_KDAL_TARGETS_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)
get_filename_component(_KDAL_ROOT "${_KDAL_TARGETS_DIR}/../../.." ABSOLUTE)

# ── KDAL runtime library ──────────────────────────────────────────────
add_library(KDAL::libkdal STATIC IMPORTED)
set_target_properties(KDAL::libkdal PROPERTIES
    IMPORTED_LOCATION
        "${_KDAL_ROOT}/build/libkdal.a"
    INTERFACE_INCLUDE_DIRECTORIES
        "${_KDAL_ROOT}/include"
    INTERFACE_COMPILE_OPTIONS
        ""
    IMPORTED_CONFIGURATIONS
        "RELEASE;DEBUG"
)

# Debug variant (optional — falls back to release if not present)
set_property(TARGET KDAL::libkdal APPEND PROPERTY
    IMPORTED_CONFIGURATIONS DEBUG)
set_target_properties(KDAL::libkdal PROPERTIES
    IMPORTED_LOCATION_DEBUG   "${_KDAL_ROOT}/build/libkdal_d.a"
    IMPORTED_LOCATION_RELEASE "${_KDAL_ROOT}/build/libkdal.a"
)

# ── KDAL compiler library (libkdalc.a) ────────────────────────────────
add_library(KDAL::libkdalc STATIC IMPORTED)
set_target_properties(KDAL::libkdalc PROPERTIES
    IMPORTED_LOCATION
        "${_KDAL_ROOT}/compiler/libkdalc.a"
    INTERFACE_INCLUDE_DIRECTORIES
        "${_KDAL_ROOT}/compiler/include"
)

# ── kdality binary ────────────────────────────────────────────────────
add_executable(KDAL::kdality IMPORTED)
set_target_properties(KDAL::kdality PROPERTIES
    IMPORTED_LOCATION "${_KDAL_ROOT}/tools/kdality/kdality"
)

# ── kdalc binary ──────────────────────────────────────────────────────
add_executable(KDAL::kdalc IMPORTED)
set_target_properties(KDAL::kdalc PROPERTIES
    IMPORTED_LOCATION "${_KDAL_ROOT}/compiler/kdalc"
)

# ── Convenience alias: KDAL::compiler is the same as KDAL::kdalc ──────
add_executable(KDAL::compiler ALIAS KDAL::kdalc)
