# KDALConfigVersion.cmake
# Semantic versioning compatibility check for find_package(KDAL <version>).
#
# Generated by the KDAL build system. This file encodes the installed
# version and implements the compatibility policy.
#
# Compatibility policy: SAME_MAJOR_VERSION
#   - Major version must match exactly.
#   - Minor/patch version of installed package must be >= requested version.
#
# Example:
#   find_package(KDAL 0.1 REQUIRED)   # succeeds if installed ≥ 0.1.x
#   find_package(KDAL 1.0 REQUIRED)   # fails if installed 0.x

set(PACKAGE_VERSION "0.1.0")

# Check whether the requested PACKAGE_FIND_VERSION is compatible.
if(PACKAGE_FIND_VERSION_MAJOR)
    if(NOT PACKAGE_FIND_VERSION_MAJOR EQUAL 0)
        # Major version mismatch — always incompatible
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
        return()
    endif()
endif()

# Full semantic version comparison
if(PACKAGE_FIND_VERSION)
    if(PACKAGE_VERSION VERSION_LESS PACKAGE_FIND_VERSION)
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
    elseif(PACKAGE_FIND_VERSION_EXACT AND
           NOT PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION)
        set(PACKAGE_VERSION_COMPATIBLE FALSE)
        set(PACKAGE_VERSION_UNSUITABLE TRUE)
    else()
        set(PACKAGE_VERSION_COMPATIBLE TRUE)
        set(PACKAGE_VERSION_EXACT
            (PACKAGE_VERSION VERSION_EQUAL PACKAGE_FIND_VERSION))
    endif()
else()
    # No version requested — always compatible
    set(PACKAGE_VERSION_COMPATIBLE TRUE)
endif()

# Expose for downstream use
set(KDAL_VERSION "${PACKAGE_VERSION}" CACHE STRING "Installed KDAL version")
